### ISSUE TITLE
Stack smashing detected

### ISSUE THREAD

**Issue by copitz** [Dockerizing/php-5.6-fpm-odbc-virtuoso#1]
Hi,

using this docker-compose setup

```yaml
version: '3.2'
volumes:
  virtuoso_lib:
  ontowiki:
services:
  virtuoso:
    image: tenforce/virtuoso
    environment:
      DBA_PASSWORD: admin
      SPARQL_UPDATE: "true"
    volumes:
      - "virtuoso_lib:/usr/local/virtuoso-opensource/lib"

  ontowiki_php:
    image: aksw/php-5.6-fpm-odbc-virtuoso
    depends_on:
      - virtuoso
      - ontowiki
    volumes:
      - "ontowiki:/var/www/html"
      - "virtuoso_lib:/usr/local/virtuoso-opensource/lib"
    links:
      - virtuoso

  ontowiki_nginx:
    image: aksw/nginx-ontowiki
    depends_on:
      - ontowiki_php
    volumes:
      - "ontowiki:/var/www/html"
    links:
      - ontowiki_php:phpserver
    ports:
      - "8080:80"

  ontowiki:
    image: aksw/ontowiki
    links:
      - virtuoso
    volumes:
      - "ontowiki:/var/www/html"
    environment:
      VIRTUOSO_ENV_DBA_PASSWORD: admin
```

I'm getting a stack smashing detected error from php-fpm:
```
ontowiki_php_1         | [08-Jan-2018 12:32:22] WARNING: [pool www] child 88 said into stderr: "*** stack smashing detected ***: php-fpm: pool www terminated"
ontowiki_php_1         | [08-Jan-2018 12:32:22] WARNING: [pool www] child 88 said into stderr: "======= Backtrace: ========="
ontowiki_php_1         | [08-Jan-2018 12:32:22] WARNING: [pool www] child 88 said into stderr: "/lib/x86_64-linux-gnu/libc.so.6(+0x731af)[0x7f08b97441af]"
ontowiki_php_1         | [08-Jan-2018 12:32:22] WARNING: [pool www] child 88 said into stderr: "/lib/x86_64-linux-gnu/libc.so.6(__fortify_fail+0x37)[0x7f08b97c9aa7]"
ontowiki_php_1         | [08-Jan-2018 12:32:22] WARNING: [pool www] child 88 said into stderr: "/lib/x86_64-linux-gnu/libc.so.6(__fortify_fail+0x0)[0x7f08b97c9a70]"
ontowiki_php_1         | [08-Jan-2018 12:32:22] WARNING: [pool www] child 88 said into stderr: "/usr/local/virtuoso-opensource/lib/virtodbc.so(+0x205c4)[0x7f08b05825c4]"
ontowiki_php_1         | [08-Jan-2018 12:32:22] WARNING: [pool www] child 88 said into stderr: "/usr/lib/x86_64-linux-gnu/libodbc.so.2(SQLColAttribute+0x303)[0x7f08b5cf07c3]"
ontowiki_php_1         | [08-Jan-2018 12:32:22] WARNING: [pool www] child 88 said into stderr: "/usr/lib/php5/20131226/odbc.so(odbc_bindcols+0xee)[0x7f08b5f56e4e]"
ontowiki_php_1         | [08-Jan-2018 12:32:22] WARNING: [pool www] child 88 said into stderr: "/usr/lib/php5/20131226/odbc.so(zif_odbc_exec+0x1ab)[0x7f08b5f57d1b]"
ontowiki_php_1         | [08-Jan-2018 12:32:22] WARNING: [pool www] child 88 said into stderr: "php-fpm: pool www(dtrace_execute_internal+0x2a)[0x6e7d5a]"
ontowiki_php_1         | [08-Jan-2018 12:32:22] WARNING: [pool www] child 88 said into stderr: "php-fpm: pool www[0x7a8740]"
ontowiki_php_1         | [08-Jan-2018 12:32:22] WARNING: [pool www] child 88 said into stderr: "php-fpm: pool www(execute_ex+0x40)[0x736a90]"
ontowiki_php_1         | [08-Jan-2018 12:32:22] WARNING: [pool www] child 88 said into stderr: "php-fpm: pool www(dtrace_execute_ex+0x78)[0x6e7bf8]"
ontowiki_php_1         | [08-Jan-2018 12:32:22] WARNING: [pool www] child 88 said into stderr: "php-fpm: pool www(zend_execute_scripts+0x180)[0x6fa7e0]"
ontowiki_php_1         | [08-Jan-2018 12:32:22] WARNING: [pool www] child 88 said into stderr: "php-fpm: pool www(php_execute_script+0x290)[0x695a00]"
ontowiki_php_1         | [08-Jan-2018 12:32:22] WARNING: [pool www] child 88 said into stderr: "php-fpm: pool www(main+0x131f)[0x464e7f]"
ontowiki_php_1         | [08-Jan-2018 12:32:22] WARNING: [pool www] child 88 said into stderr: "/lib/x86_64-linux-gnu/libc.so.6(__libc_start_main+0xf5)[0x7f08b96f2b45]"
ontowiki_php_1         | [08-Jan-2018 12:32:22] WARNING: [pool www] child 88 said into stderr: "php-fpm: pool www[0x465599]"
```

I'm getting this error when I open localhost:8080 as well as with the [testodbc.php file](http://docs.ontowiki.net/VirtuosoBackend.html#setting-up-odbc)
